### ISSUE TITLE
Erreur sur un jour 2023-3-6

### ISSUE THREAD

**Issue by domo-home** [grimmlink/tempo-comparatif#10]
Bonjour, 

Merci pour le super travail que tu as réalisé, cel me permet de voir les économies que je vais pouvoir réaliser en passant sur l'offre Tempo.

Je pense qu'il y a une toute petite erreur pour le 06-03-2023.
En effet, il est indiqué comme bleu dans le fichier Json, alors qu'il est Blanc sur le site de EDF.

![image](https://github.com/grimmlink/tempo-comparatif/assets/64208224/4e145811-fec7-4df0-88d9-1ba1e827d5b7)

![image](https://github.com/grimmlink/tempo-comparatif/assets/64208224/af5d7320-9f55-438a-ae49-3bc0b1606adb)

Bonne journée.

**Comment by grimmlink** [comment]
Bonjour,

En effet, c'est bizarre car je récupère les données sur le site d'enedis.. J'ai mis a jour le fichier, ca devrait etre ok.

Merci pour ton retour

**Comment by domo-home** [comment]
De rien, mais quelle rapidité :) 

Pierre
