### ISSUE TITLE
Erreur Uncaught Error: Call to a member function format() on bool

### ISSUE THREAD

**Issue by grandyoz** [grimmlink/tempo-comparatif#13]
Bonjour,
J'ai cette erreur quand j'essaye d'utiliser cette page : https://tarifelec.vraiment.top/

Fatal error: Uncaught Error: Call to a member function format() on bool in /var/www/html/index.php:87 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 87

Est-ce possible de corriger ça ?

Merci d'avance pour votre aide !

**Comment by grimmlink** [comment]
Bonjour,

Etes-vous sur d'avoir uploadé le bon fichier ?
Il faut mettre le fichier de conso horaire.

**Comment by domo-home** [comment]
Bonjour, 
Avez vous supprimé les 3 premières lignes de votre fichier ?

**Comment by grandyoz** [comment]
Bonjour,
Non, effectivement c'est un fichier par jour avec index HC et HP.
Je comprends mieux du coup pourquoi ! Peut-être est-ce possible de l'indiquer plus précisément ?

J'ai fais un script python pour analyser mes données et coup, j'ai récupéré l'info autrement !

Merci beaucoup en tout cas d'avoir mis cet outils à disposition !

Bonne journée
