### ISSUE TITLE
Error in PHP call

### ISSUE THREAD

**Issue by Ririwin** [grimmlink/tempo-comparatif#14]
error loading calculation.
the problem comes from the ENEDIS csv or from reading the date

>Fatal error: Uncaught Error: Call to a member function format() on bool in /var/www/html/index.php:87 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 87

**Comment by domo-home** [comment]
Please remove the first 3 lines of the CSV file, and do it again :)

**Comment by grimmlink** [comment]
@Ririwin I think you have the wrong export file from Enedis, pls use the "consommation horaire"

@domo-home plus besoin de supprimer les lignes ;)

**Comment by peripatetic** [comment]
Hello all, 

I'm getting a different PHP error:

`Fatal error: Uncaught TypeError: Unsupported operand types: float * string in /var/www/html/index.php:156 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 156`

I tried deleting the first three lines and made sure it was consommation horaire, but I still get the error.

**Comment by Pschittt** [comment]
Bonjour,

L'erreur est toujours présente, aussi bien en supprimant les 3 premières lignes qu'en les laissant.

**Comment by grimmlink** [comment]
Bonjour @Pschittt ,

Avez-vous bien exporté le bon fichier ? (consommation horaire)

**Comment by Pschittt** [comment]
En effet ! l'erreur vient bien de là. Mes excuses.
