### ISSUE TITLE
Différences entre le calcul effectué par https://tarifelec.vraiment.top/ et le site d'Enedis

### ISSUE THREAD

**Issue by mooms06** [grimmlink/tempo-comparatif#15]
Enedis me donne une consommation de 3911 kWh pour 2023:

![image](https://github.com/grimmlink/tempo-comparatif/assets/25405517/3b64b500-989d-4488-9470-ba6d41cb2f87)

https://tarifelec.vraiment.top/ calcule 3898.046 kWh  à partir du ficher CSV de Enedis:

![image](https://github.com/grimmlink/tempo-comparatif/assets/25405517/8382bbcc-f40c-4913-9fb6-14e1ab5d163c)

Une explication sur cette différence ?

**Comment by domo-home** [comment]
Bonjour, 
Est ce que tu as toutes les valeurs dans le fichier CSV ? Il s'arrête bien au 31/12 à 23h30 ?

**Comment by mooms06** [comment]
Non effectivement, il s'arrête à 00:00, il manque toute la journée du 31/12,  ça explique la différence.
Les deux dernières lignes:

```
2023-12-30T23:30:00+01:00;2466
2023-12-31T00:00:00+01:00;2186

```

Bien vu !
