### ISSUE TITLE
Le tarif de l'abonnement HP/HC est pour 9 kVA, quand les autres sont pour 6 kVA

### ISSUE THREAD

**Issue by slasherfun** [grimmlink/tempo-comparatif#16]
Bonjour,

Si le tarif des abonnements base (12,60€/mois), Tempo (12,96€/mois), et ZenFlex (13,03€/mois) correspond à une puissance souscrite de 6 kVA, celui de l'abonnement HP/HC (16,70€/mois) est celui d'une puissance de 9 kVA.
Il serait plus logique d'utiliser ici également le tarif d'un abonnement 6 kVA (13,01€/mois).

https://github.com/grimmlink/tempo-comparatif/blob/cb89cf214f815bb898ed36517d6bcc1af7fcdc2e/index.php#L53C1-L53C39

**Comment by grimmlink** [comment]
Bonjour,

En effet, c'est corrigé ! Merci !
