### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function format() on bool in /var/www/html/index.php:27 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 27

### ISSUE THREAD

**Issue by osantiano** [grimmlink/tempo-comparatif#2]
Now on [vraiment.top](https://tarifelec.vraiment.top/)

With a legit Enedis hourly file (536ko)

**Comment by grimmlink** [comment]
Hi, You have to remove the first lines of the file in order to only keep consumption data

**Comment by osantiano** [comment]
Super, merci !
