### ISSUE TITLE
Fonctionnement Tempo

### ISSUE THREAD

**Issue by saiyajin59** [grimmlink/tempo-comparatif#3]
Hello,
Je voudrais savoir comment le site calcule l'économie avec Tempo ?
ça se base sur les jours de quelles couleurs pour le calcule ?
J’imagine que ça ne prend pas pas l'historique des jours de couleurs sur le calendrier officiel EDF tempo pour comparer ?

Merci !

**Comment by grimmlink** [comment]
Bonjour,

L'export Enedis permet de calculer la conso sur une periode horaire, donc en sachant que les heures tempos sont HP 6h-22h et HC 22h-6h, on peut calculer précisément ce que ca nous aurait couté avec tempo.

Actuellement j'ai un fichier JSON ([celui-ci](https://github.com/grimmlink/tempo-comparatif/blob/master/tempo.json)) que je mets a jour régulièrement avec l'historique des couleurs Tempo, mais je suis en train de voir pour trouver un moyen dynamique pour que ca tourne tout seul.

TL;DR : oui c'est calculé précisement avec les couleurs tempo :)

**Comment by saiyajin59** [comment]
Ah oui j'avais pas vu le json.
C'est top !
GG pour cet outil, la data est donc fiable, je vais faire des économies xD

**Comment by grimmlink** [comment]
Oui normalement c'est fiable :)

Y a aussi une autre version qui a été developpée dur https://tarifelec.vraiment.top/ ca permet de comparer le resultat
