### ISSUE TITLE
Mauvaise couleur TEMPO

### ISSUE THREAD

**Issue by Gnaagounet** [grimmlink/tempo-comparatif#4]
Hello,

Merci pour ton script dont je me sers pour comparer les éventuelles économies faites en passant à une offre TEMPO. Toutefois, je constate que quelque soit les périodes choisies, des économies sont faites (alors que je ne fais actuellement pas attention à cette consommation). En testant par exemple la journée du 08/02/2023 (TEMPO ROUGE), de 08h00 a 20h00, le script m'annonce une économie de 1.81%. En téléchargeant le détail, celui-ci me donne une couleur TEMPO BLEU alors que dans le JSON cette date est bien en TEMPO ROUGE.

Ci joint le détail.
[detail(2).csv](https://github.com/grimmlink/tempo-comparatif/files/10897111/detail.2.csv)

Source du calendrier TEMPO : 
https://particulier.edf.fr/fr/accueil/gestion-contrat/options/tempo.html#/selection-bp

**Comment by saiyajin59** [comment]
Hello,
Je constate la même erreur

**Comment by grimmlink** [comment]
Hello,

En effet jolie trouvaille, le format de date n'etait pas bon dans le code pour trouver la bonne couleur, donc chaque mois les 9 premiers jours etaient comptés bleus !

Pas un gros impact sur une période d'un an je pense, mais si on regarde que l'hiver ca change tout.

C'est corrigé, merci !

**Comment by Gnaagounet** [comment]
Top merci je ferai un nouvel essai 👍
