### ISSUE TITLE
Mauvaise determination des couleurs Blau Blanc Rouge

### ISSUE THREAD

**Issue by Xtofe2000** [grimmlink/tempo-comparatif#5]
Bonjour
Je me rends compte que le calcul du tempo est erroné:
Pour des journées, on a des jours d'une couleur de 0:00 à 6:00, encadré d'une autre couleur..
[Detail_1.csv](https://github.com/grimmlink/tempo-comparatif/files/11189164/Detail_1.csv)
(20-21-22/12/2021 sont rouges)

[Detail_3.csv](https://github.com/grimmlink/tempo-comparatif/files/11189204/Detail_3.csv)
(04/01/2022 Bleu et 05/01/2022 Blanc)

Des journées d'une couleur de 0:00 à 0:00 encadrées d'une autre couleur ..
[Detail_4.csv](https://github.com/grimmlink/tempo-comparatif/files/11189242/Detail_4.csv)
(08-09/01/2022 Bleu et 10/01/2022 Rouge)

Couleur des journée récupérés sur ce site 
[Kell Watt](https://www.kelwatt.fr/fournisseurs/edf/tempo)

De plus quand je regarde le détails des montant/kWh, je ne vois pas apparaître le prix de l'abo, que le prix du kWh ( pour le Tempo, j'ai pas regardé pour les autres en fait, abo de 6kW pour moi )....

J'ai réalisé l'exercice sur 2022, j'ai un écart de 30% par rapport à la feuille, c’est dommage car c'est très intéressant de connaitre l'écart de prix ....
SLT

**Comment by grimmlink** [comment]
Bonjour @Xtofe2000 ,

En effet il y avait un soucis dans la determination de la date pour tempo, je viens de corriger.
Le site sera mis a jour bientot !

Merci pour le retour !

**Comment by Xtofe2000** [comment]
@grimmlink 
Trop Cool, car c'est un super outils de calcul pour comparer les tarifs ...

je viens de voir que l'abo était donné sur la page, par dans le fichier.csv, donc pour moi, ce n'est pas un soucis ...

**Comment by grimmlink** [comment]
Oui je ne mets pas l'abo dans le CSV, car il faudrait calculer le prorata sur cahque ligne, ce serait assez compliqué

**Comment by Xtofe2000** [comment]
@grimmlink 
Je viens de vérifier : C'est cool, cela fonctionne, pas d'erreur !
