### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by alpha13fr** [grimmlink/tempo-comparatif#8]
Bonjour,
J'ai cette erreur 👍 Fatal error: Uncaught Error: Call to a member function format() on bool in /var/www/html/index.php:180 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 180

j'ai bien enlevé les 3 premieres lignes

Merci

**Comment by grimmlink** [comment]
Bonjour,

Etes-vous sur d'avoir exporté le bon fichier ?  Il faut le fichier de consommation horaire
