### ISSUE TITLE
Valeur divisée par 2 lorsque relevé par 1/2 heure

### ISSUE THREAD

**Issue by alpha13fr** [grimmlink/tempo-comparatif#9]
Bonjour,
Les relevés horaires sont en 1/2 h ou j'ai louper une option !
Avec ces releves par 1/2 heure, pourquoi les 2 valeurs de la tranche horaire sont elles divisées par 2 alors qu'elle devrait etre prise en compte ?
Merci

mon releve 
2023-02-02T02:00:00+02:00;289
2023-02-02T03:00:00+02:00;542
2023-02-02T03:30:00+02:00;200
2023-02-02T04:00:00+02:00;395

le tableau excel resultant 
2023-02-02T02:00:00+02:00 | 0.289
2023-02-02T03:00:00+02:00 | 0.271
2023-02-02T03:30:00+02:00 | 0.1
2023-02-02T04:00:00+02:00 | 0.395

**Comment by grimmlink** [comment]
Bonjour,

Interessant, on a un periode d'une heure, au milieu de periodes de 30minutes (c'est bien souvent des periodes de 30mn, mais ca peut être 45mn, 1h... merci Enedis)

Pour la valeur du 2023-02-02T03:30:00+02:00;200 qui est divisée par deux, c'est normal. Explication : 
Les tarifs sont données pour 1KWh, mais on a une conso en W pour 30 minutes. Donc on divise la valeur par 1000 pour obtenir des KW, puis par 2 pour avoir la valeur en KWh (la conso de 200W sur 30mn equivaut a 0.1KWh)

Ce qui explique pour la 1ere valeur 289 n'est pas changée, l'ecart etant d'une heure avec la valeur suivante.
J'imagine que c'est pareil pour la derniere valeur, l'ecarta vec la suivante doit être d'une heure aussi (valeur non changée)
